close all; clear; clc;
db = {'IAPRTC-12'};
hashmethods = {'OCEAN'};
param.nbits = 16;
param.top_K = 2000;
[XChunk,YChunk,LChunk,XTest,YTest,LTest,chunks] = load_data(db);
fprintf('========%s %d bits start======== \n', 'OCEAN',param.nbits);
OCEANparam = param;
OCEANparam.nchunks=chunks;
OCEANparam.theta=0.5;
OCEANparam.alpha=1e4;
OCEANparam.beta=1e0; 
OCEANparam.mu=1e5;
eva_info_ = evaluate_OCEAN(XChunk,YChunk,LChunk,XTest,YTest,LTest,OCEANparam);
fprintf('Image_VS_Text_MAP: %6.4f.\n', eva_info_{9}.Image_VS_Text_MAP);
% evaluation_info.Image_VS_Text_MAP50 = mAP(orderH', LTrain, LTest, 50);
fprintf('Image_VS_Text_MAP100: %6.4f.\n', eva_info_{9}.Image_VS_Text_MAP100);
fprintf('Text_VS_Image_MAP: %6.4f.\n', eva_info_{9}.Text_VS_Image_MAP);
% evaluation_info.Text_VS_Image_MAP50 = mAP(orderH', LTrain, LTest, 50);
fprintf('Text_VS_Image_MAP100: %6.4f.\n', eva_info_{9}.Text_VS_Image_MAP100);

